### ISSUE TITLE
Using version tags in python requirements

### ISSUE THREAD

**Issue by T-Thurow** [tbohne/vehicle_diag_smach#18]
The requirements.txt currently references the upstream version of ```obd_ontology``` and ```oscillogram_classification``` which are prone to change.

It would be better to reference specific version tags or commit hashes to keep older commits build clean in case there are API changes for ```obd_ontology``` or```oscillogram_classification```.

**Comment by tbohne** [comment]
I agree, did that. However, at the moment it doesn't make a difference as the latest versions are the ones that are supposed to be used.

**Comment by T-Thurow** [comment]
I see. We are currently trying to maintain a stable branch of our code which should always be build clean. The ```vehicle_diag_smach``` was frozen to commit 4c2b043ef336a58471f652c8199efefa3aef84e6 which was a working state at merge time  but it started failing because of the config module bug in ```oscillogram_classification``` and since you fixed that it crashed because ```local_kb``` was removed from ```OntologyInstanceGenerator``` in ```obd_ontology``` which the frozen code still had. 
For the sake of stability a changing version tag seems like a good way to preserve a working state.
An package index like pypi would also be good. Have you considered publishing to a package index in the long run?
